server:
  port: 8080
spring:
  data:
    redis:
      database: 8
      host: 172.16.2.10
      port: 6379
      password: c1$4T&9pW#z2Q@7vL
      timeout: 5s
      connect-timeout: 5s
  session:
    timeout: 43200s
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orchid?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: admin
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
      connection-test-query: SELECT 1
      pool-name: DatebookHikariCP
  messages:
    basename: i18n/commons,i18n/api,i18n/bug,i18n/case,i18n/plan,i18n/project,i18n/system
logging:
  level:
    web: debug
    org.springframework.security: trace
mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
springdoc:
  api-docs:
    enabled: true